import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AuthProvider from "./components/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Event Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Main container */}
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />

            {/* Page content */}
            <main className="flex-1">
              {children}
            </main>

            <Footer />
          </div>



        </AuthProvider>
      </body>
    </html>
  );
}
